name: Publish to PyPI on Release

on:
  release:
    types: [published]   # runs when you publish a GitHub Release

permissions:
  id-token: write        # REQUIRED for PyPI Trusted Publisher (OIDC)
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print_hash: true
