name: Publish to PyPI on Release

on:
  release:
    types: [published]

permissions:
  id-token: write  
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug pyproject.toml
        run: |
          echo "----- locations -----"
          find . -name pyproject.toml -maxdepth 3 -print
          echo "----- numbered -----"
          nl -ba pyproject.toml
          echo "----- tomllib parse -----"
          python - <<'PY'
          import tomllib, pathlib
          b = pathlib.Path("pyproject.toml").read_bytes()
          cfg = tomllib.loads(b.decode("utf-8"))
          proj = cfg.get("project", {})
          print("project.name:", proj.get("name"))
          print("project.version:", proj.get("version"))
          print("pyproject parsed OK")
          PY

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          python -m twine check dist/*

      - name: Show built artifacts
        run: ls -l dist && shasum -a 256 dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print_hash: true
