name: Publish to PyPI on Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      #  print exactly what the runner sees
      - name: Debug pyproject.toml
        run: |
          echo "----- locations -----"
          find . -name pyproject.toml -maxdepth 3 -print
          echo "----- numbered -----"
          nl -ba pyproject.toml
          echo "----- hexdump (first 80 lines) -----"
          hexdump -C pyproject.toml | sed -n '1,200p'
          echo "----- tomllib parse -----"
          python - <<'PY'
          import tomllib, pathlib, sys
          p = pathlib.Path("pyproject.toml")
          b = p.read_bytes()
          print(b.decode("utf-8", "backslashreplace"))
          tomllib.loads(b.decode("utf-8"))
          print("TOML parsed OK by tomllib")
          PY

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print_hash: true
